# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Ryadar' do

  use_frameworks!

  pod 'SVProgressHUD'
  target 'RyadarTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RyadarUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
